global using GasNetwork.Models;
global using GasNetwork.ViewModels;
global using GasNetwork.Views;
global using GasNetwork.Services;
global using GasNetwork.Interfaces;
global using GasNetwork.Enums;
global using GasNetwork.Attributes;
global using GasNetwork.Converters;
global using GasNetwork.Extensions;